### ISSUE TITLE
Self-signed certificate not working

### ISSUE THREAD

**Issue by sdargoeuves** [community-fabric/python-ipfabric#148]
The test below works on SDK ipfabric<=5.0.2, but not from 5.0.3.

```
from ipfabric import IPFClient
ipf = IPFClient(base_url="https://192.168.47.131", token=my_token, verify=False)
```

from version 5.0.3, I get this error message:

> `ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:997)`

**Comment by justinjeffery-ipf** [comment]
Should have been fixed in 5.0.7 and up

**Comment by sdargoeuves** [comment]
I have the same error with SDK 5.0.7 or 5.0.10:
`ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:997)`

**Comment by justinjeffery-ipf** [comment]
#149
