### ISSUE TITLE
Handy Functions to Have

### ISSUE THREAD

**Issue by minitriga** [community-fabric/python-ipfabric#157]
When developing the Ansible Collection there are a bunch of endpoints that are not implemented. I will get round to implementing them but would be good to know what you think. 

- `get_snapshot` - get snapshot by id (snapshot_id)
- `create_snapshot` - Start a snapshot (snapshot_id[str], name[str], note[str], devices[list], settings[dict])
- `delete_snapshot` - Delete a snapshot
- `snapshot_actions` - Perform snapshot actions? (snapshot_id[str], state[enum] (lock, unlock, clone, load, unload))

**Comment by justinjeffery-ipf** [comment]
- get_snapshot - get snapshot by id (snapshot_id)
  - ipf.snapshots[<ID>]
- Snapshots - Create, Delete, Modify, Clone
  - #17 Snapshot Creation/Manipulation/Deletion
- snapshot_actions - Perform snapshot actions? (snapshot_id[str], state[enum] (lock, unlock, clone, ))
  - load, unload implemented - Need to add jobs to check status
  - lock/unlock to be added in v6.0

**Comment by justinjeffery-ipf** [comment]
Opened new issues
